name = "20260822-tongin"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

# Cloudflare D1 바인딩 설정
[[d1_databases]]
binding = "DB"
database_name = "tongin-db"
database_id = "a3a9a59b-513a-4ba2-9f74-4dc2281b5b05"

# Cloudflare R2 바인딩 설정
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tongin-bucket"

[vars]
NEXT_PUBLIC_API_URL = "https://20260822-tongin.pages.dev"

[assets]
directory = ".open-next/assets"