name = "20260822-tongin"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Cloudflare D1 바인딩 설정
[[d1_databases]]
binding = "DB"
database_name = "tongin-db"
database_id = "a3a9a59b-513a-4ba2-9f74-4dc2281b5b05"

# Cloudflare R2 바인딩 설정
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tongin-bucket"

[vars]
NEXT_PUBLIC_API_URL = "https://20260822-tongin.pages.dev"